# Generated by Django 3.0.5 on 2020-05-21 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('discipline', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
                ('limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
