# Generated by Django 3.0.5 on 2020-05-22 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_auto_20200521_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_tournament', to=settings.AUTH_USER_MODEL),
        ),
    ]
