# Generated by Django 3.0.5 on 2020-06-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20200522_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
    ]
