# Generated by Django 3.0.5 on 2020-06-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0005_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-tournament_level', 'id']},
        ),
        migrations.AddField(
            model_name='match',
            name='winner_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner_set_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
