# Generated by Django 3.0.5 on 2020-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20200614_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.CharField(default='admin', max_length=128),
            preserve_default=False,
        ),
    ]
